version: '{build}'
skip_tags: true
image:
- Visual Studio 2017
- Ubuntu1804

platform:
  - Win32
  - x86
  - x64
configuration: RelWithDebInfo

matrix:
  exclude:
    - image: Ubuntu1804
      platform: Win32
    - image: Visual Studio 2017
      platform: x86
    - image: Visual Studio 2017
      platform: x64
init:
- cmd: git config --global core.autocrlf true

install:
  - cmd: powershell -Command Start-FileDownload http://assets.maxmitti.tk/openclonk-deps-vs140-i386-easy.7z
  - cmd: 7z x openclonk-deps-vs140-i386-easy.7z
  - cmd: powershell -Command Start-FileDownload http://fulgen.bplaced.net/files/fmodapi375win.zip
  - cmd: 7z x fmodapi375win.zip
  - cmd: copy fmodapi375win\api\inc\* deps\include
  - cmd: copy fmodapi375win\api\lib\* deps\lib

before_build:
  - cmd: cmake -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=RelWithDebInfo .
  - cmd: ls

build:
  parallel: true
  project: LegacyClonk.sln

for:
-
  matrix:
      only:
        - image: Ubuntu1804

  build_script:
  - sh: if test "$PLATFORM" = "x86"; then sudo docker run -t -v "$(pwd)":/lc -w /lc i386/ubuntu:18.04 appveyor/build.sh; fi
  - sh: if test "$PLATFORM" = "x64"; then ./appveyor/build.sh; fi

after_build:
  - cmd: ls
  - cmd: ls RelWithDebInfo
  - cmd: mkdir appdir
  - cmd: copy glew32.dll appdir
  - cmd: copy RelWithDebInfo\*.exe appdir
  - cmd: copy RelWithDebInfo\*.pdb appdir
  - cmd: cd appdir
  - cmd: 7z a LegacyClonk.zip *
  - cmd: appveyor PushArtifact .\LegacyClonk.zip -DeploymentName LegacyClonk
  -
  - sh: cd build
  - sh: appveyor PushArtifact LegacyClonk.tar.gz -FileName LegacyClonk-${PLATFORM}.tar.gz -DeploymentName LegacyClonk
  - sh: if test "$PLATFORM" = "x64"; then C4GROUP=./c4group ../tools/make_Graphics.c4g.sh; fi
  - sh: if test "$PLATFORM" = "x64"; then appveyor PushArtifact Graphics.c4g -DeploymentName LegacyClonk; fi
  - sh: if test "$PLATFORM" = "x64"; then C4GROUP=./c4group ../tools/make_System.c4g.sh; fi
  - sh: if test "$PLATFORM" = "x64"; then appveyor PushArtifact System.c4g -DeploymentName LegacyClonk; fi

test: off
deploy:
- provider: GitHub
  tag: continuous-$(APPVEYOR_REPO_BRANCH)
  release: Continuous build
  auth_token:
    secure: YE0vsP2wBEPL52Fo6eOeql9XqUlWimQ6Hbw2HPAOIorw4peKSiniwoU4Dhh/vXJ+
  artifact: LegacyClonk
  prerelease: true
  force_update: true
